version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./_docker/django/development/Dockerfile
    command: bash -c "source .venv/bin/activate && python3 setup.py develop && integreat-cms runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    ports:
      - 8000:8000
    restart: always
    #tty: true
    volumes:
      - "./backend:/opt/integreat-cms/backend"

  postgres:
    environment:
      - POSTGRES_USER=integreat
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=integreat
    image: postgres
    restart: always
    volumes:
      - "./_postgres:/var/lib/postgresql"
