# Generated by Django 3.2.11 on 2022-01-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
        CREATE TYPE public.translation_state AS ENUM
            ('in_translation', 'outdated', 'up_to_date', 'missing');

        ALTER TYPE public.translation_state
            OWNER TO integreat;

        """
        ),
        migrations.RunSQL(
            """
        CREATE OR REPLACE FUNCTION public.get_last_major_public_revion(
            in_page_id bigint,
            in_language_id bigint)
            RETURNS cms_pagetranslation
            LANGUAGE 'sql'
            COST 100
            VOLATILE PARALLEL UNSAFE
        AS $BODY$
        SELECT * FROM cms_pagetranslation WHERE page_id = in_page_id AND language_id = in_language_id AND status = 'PUBLIC' AND minor_edit = False ORDER BY last_updated DESC LIMIT 1
        $BODY$;

        ALTER FUNCTION public.get_last_major_public_revion(bigint, bigint)
            OWNER TO integreat;

        """
        ),
        migrations.RunSQL(
            """
        CREATE OR REPLACE FUNCTION public.get_last_major_public_revion_updated(
            in_page_id bigint,
            in_language_id bigint)
            RETURNS timestamp with time zone
            LANGUAGE 'sql'
            COST 100
            VOLATILE PARALLEL UNSAFE
        AS $BODY$
        SELECT last_updated FROM cms_pagetranslation WHERE page_id = in_page_id AND language_id = in_language_id AND status = 'PUBLIC' AND minor_edit = False ORDER BY last_updated DESC LIMIT 1
        $BODY$;

        ALTER FUNCTION public.get_last_major_public_revion_updated(bigint, bigint)
            OWNER TO integreat;
        """
        ),
        migrations.RunSQL(
            """
        CREATE OR REPLACE FUNCTION public.get_region_languages(
            region_id bigint)
            RETURNS bigint[]
            LANGUAGE 'sql'
            COST 100
            VOLATILE PARALLEL UNSAFE
        AS $BODY$
        SELECT 
            ARRAY_AGG(cms_languagetreenode.language_id)
        FROM cms_languagetreenode
        WHERE cms_languagetreenode.region_id = $1
        group by cms_languagetreenode.region_id
        $BODY$;

        ALTER FUNCTION public.get_region_languages(bigint)
            OWNER TO integreat;
        """
        ),
        migrations.RunSQL(
            """
        CREATE OR REPLACE FUNCTION public.get_source_language(
            in_language_id bigint,
            in_region_id bigint)
            RETURNS bigint
            LANGUAGE 'sql'
            COST 100
            VOLATILE PARALLEL UNSAFE
        AS $BODY$
        SELECT
            parent.language_id
        from cms_languagetreenode
            JOIN cms_languagetreenode parent ON parent.id = cms_languagetreenode.parent_id
            WHERE cms_languagetreenode.language_id = in_language_id 
            AND cms_languagetreenode.region_id = in_region_id 
        LIMIT 1
        $BODY$;

        ALTER FUNCTION public.get_source_language(bigint, bigint)
            OWNER TO integreat;
        """
        ),
        migrations.RunSQL(
            """
        CREATE OR REPLACE FUNCTION public.get_translation_state(
            in_page_id bigint,
            in_language_id bigint,
            in_region_id bigint)
            RETURNS translation_state
            LANGUAGE 'sql'
            COST 100
            VOLATILE PARALLEL UNSAFE
        AS $BODY$
        SELECT COALESCE(
            (SELECT 
                CASE
                WHEN COUNT(*) = 0 THEN 'missing'::translation_state
                WHEN cms_pagetranslation.currently_in_translation THEN 'in_translation'::translation_state
                WHEN get_source_language(in_language_id, in_region_id) IS NOT NULL AND get_translation_state(in_page_id, get_source_language(in_language_id, in_region_id), in_region_id) = 'outdated'::translation_state THEN 'outdated'::translation_state
                WHEN 
                        get_source_language(in_language_id, in_region_id) IS NOT NULL
                    AND get_last_major_public_revion_updated(in_page_id, in_language_id) < get_last_major_public_revion_updated(in_page_id, get_source_language(in_language_id, in_region_id))
                    THEN 'outdated'::translation_state
                ELSE 'up_to_date'::translation_state
                END
            from cms_pagetranslation where page_id = in_page_id AND language_id = in_language_id
            GROUP BY page_id, language_id, currently_in_translation
            LIMIT 1)
        , 'missing'::translation_state)
        $BODY$;

        ALTER FUNCTION public.get_translation_state(bigint, bigint, bigint)
            OWNER TO integreat;

        """
        ),
        migrations.RunSQL(
            """
        CREATE OR REPLACE VIEW public.page_translation_state
        AS
        SELECT cms_page.id AS page_id,
            cms_page.region_id,
            cms_language.id AS language_id,
            get_translation_state(cms_page.id, cms_language.id, cms_region.id) AS translation_state
        FROM cms_page,
            cms_language,
            cms_region
        WHERE cms_region.id = cms_page.region_id;

        ALTER TABLE public.page_translation_state
            OWNER TO integreat;
        """
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW public.page_translation_state_flat
            AS
            SELECT cms_page.id,
                cms_page.explicitly_archived,
                cms_page.created_date,
                cms_page.mirrored_page_first,
                cms_page.lft,
                cms_page.rght,
                cms_page.tree_id,
                cms_page.level,
                cms_page.icon_id,
                cms_page.mirrored_page_id,
                cms_page.organization_id,
                cms_page.parent_id,
                cms_page.region_id,
                json_object_agg(page_translation_state.language_id, page_translation_state.translation_state) AS translation_state
            FROM page_translation_state
                JOIN cms_page ON cms_page.id = page_translation_state.page_id
            GROUP BY page_translation_state.page_id, cms_page.id;

            ALTER TABLE public.page_translation_state_flat
                OWNER TO integreat;
        """
        ),
    ]
