# Generated by Django 3.2.12 on 2022-02-12 16:36

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    """
    Change the ordering of models
    """

    dependencies = [
        ("cms", "0003_remove_imprintpage_explicitly_archived"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offertemplate",
            options={
                "default_permissions": ("change", "delete", "view"),
                "ordering": ["slug"],
                "verbose_name": "offer template",
                "verbose_name_plural": "offer templates",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "default_permissions": ("change", "delete", "view"),
                "ordering": ["slug"],
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="poi",
            options={
                "default_permissions": ("change", "delete", "view"),
                "default_related_name": "pois",
                "ordering": ["pk"],
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.AlterModelOptions(
            name="pushnotification",
            options={
                "default_permissions": ("change", "delete", "view"),
                "ordering": ["-created_date"],
                "permissions": (
                    ("send_push_notification", "Can send push notification"),
                ),
                "verbose_name": "push notification",
                "verbose_name_plural": "push notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="recurrencerule",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "recurrence rule",
                "verbose_name_plural": "recurrence rules",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "default_permissions": (),
                "ordering": ["name"],
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": ("change", "delete", "view"),
                "ordering": ["username"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterModelOptions(
            name="usermfakey",
            options={
                "default_permissions": (),
                "ordering": ["name"],
                "verbose_name": "multi-factor authentication key",
                "verbose_name_plural": "multi-factor authentication keys",
            },
        ),
    ]
