# Generated by Django 3.2.12 on 2022-03-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add two new translation fields to the language model.
    These are shown to the user when a mirrored page is not available in the selected language.
    """

    dependencies = [
        ("cms", "0013_require_pushnotificationtranslation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="message_live_content_not_available",
            field=models.CharField(
                default="This page does not exist in the selected language. It is however available in these languages:",
                help_text="This is shown to the user when a mirrored page is not available in their language.",
                max_length=250,
                verbose_name='"This page does not exist in the selected language. It is however available in these languages:" in this language',
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="message_partial_live_content_not_available",
            field=models.CharField(
                default="Part of the page does not exist in the selected language. It is however available in these languages:",
                help_text="This is shown to the user when the mirrored part of a page is not available in their language.",
                max_length=250,
                verbose_name='"Part of the page does not exist in the selected language. It is however available in these languages:" in this language',
            ),
        ),
    ]
