# Generated by Django 3.2.12 on 2022-04-23 12:26

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This is the migration file for the timezones
    """

    dependencies = [
        ("cms", "0016_region_tunews_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="timezone",
            field=models.CharField(
                default="Europe/Berlin", max_length=150, verbose_name="timezone"
            ),
        ),
    ]
