# Generated by Django 3.2.13 on 2022-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add "locations_enabled" field to region model
    """

    dependencies = [
        ("cms", "0023_rename_message_live_content_not_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="locations_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not locations are enabled in the region",
                verbose_name="activate locations",
            ),
        ),
    ]
