# Generated by Django 3.2.12 on 2022-04-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add a new field to the region model to determine whether fallback translations should be used
    """

    dependencies = [
        ("cms", "0028_alter_user_expert_mode_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="fallback_translations_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not events and locations are shown in default language as fallback",
                verbose_name="Show content in default language as fallback",
            ),
        ),
    ]
