# Generated by Django 3.2.13 on 2022-06-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Ensure version numbers are unique for all content objects in each language.
    """

    dependencies = [
        ("cms", "0030_alter_region_aliases"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventtranslation",
            constraint=models.UniqueConstraint(
                fields=("event", "language", "version"),
                name="eventtranslation_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="imprintpagetranslation",
            constraint=models.UniqueConstraint(
                fields=("page", "language", "version"),
                name="imprintpagetranslation_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetranslation",
            constraint=models.UniqueConstraint(
                fields=("page", "language", "version"),
                name="pagetranslation_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="poitranslation",
            constraint=models.UniqueConstraint(
                fields=("poi", "language", "version"),
                name="poitranslation_unique_version",
            ),
        ),
    ]
