# Generated by Django 3.2.15 on 2022-09-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add ``summ_ai_enabled`` field to region model
    """

    dependencies = [
        ("cms", "0037_event_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="summ_ai_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether automatic translations into Easy German with SUMM.AI are enabled",
                verbose_name="activate automatic translations via SUMM.AI",
            ),
        ),
    ]
