# Generated by Django 3.2.15 on 2022-10-15 13:00

from __future__ import annotations

from django.db import migrations, models

import integreat_cms.cms.models.media.media_file


class Migration(migrations.Migration):
    """
    Add file size check
    """

    dependencies = [
        ("cms", "0039_poi_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(
                max_length=512,
                upload_to=integreat_cms.cms.models.media.media_file.upload_path,
                validators=[integreat_cms.cms.models.media.media_file.file_size_limit],
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="thumbnail",
            field=models.FileField(
                max_length=512,
                upload_to=integreat_cms.cms.models.media.media_file.upload_path_thumbnail,
                validators=[integreat_cms.cms.models.media.media_file.file_size_limit],
                verbose_name="thumbnail file",
            ),
        ),
    ]
