# Generated by Django 3.2.14 on 2022-09-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds the hix_enabled region setting to the model.
    """

    dependencies = [
        ("cms", "0040_limit_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="hix_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow users of this region to analyze understandability of text content via TextLab API.",
                verbose_name="Activate HIX analysis",
            ),
        ),
    ]
