# Generated by Django 3.2.16 on 2022-11-10 08:42

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file to make user model gender sensitive
    """

    dependencies = [
        ("cms", "0045_update_to_be_gender_sensitive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this account should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this account has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
