# Generated by Django 3.2.16 on 2022-10-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Rename short_description to meta_description, make it optional
    """

    dependencies = [
        ("cms", "0046_user_gender_sensitive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poitranslation",
            old_name="short_description",
            new_name="meta_description",
        ),
        migrations.AlterField(
            model_name="poitranslation",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Describe the location in one or two short sentences. This text will be displayed in the Google search results below the title.",
                max_length=2048,
                verbose_name="meta description",
            ),
        ),
    ]
