# Generated by Django 3.2.16 on 2023-01-26 09:53

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adding icon and color to POI Category
    """

    dependencies = [
        ("cms", "0058_translations_management_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="poicategory",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("#3700D2", "Dark blue"),
                    ("#2E98FB", "Sky blue"),
                    ("#1DC6C6", "Cyan"),
                    ("#3F8F01", "Forest green"),
                    ("#07DC03", "Lawn green"),
                    ("#F2DA04", "Yellow"),
                    ("#C38E03", "Gold"),
                    ("#FF7C32", "Orange"),
                    ("#FF3333", "Red"),
                    ("#EE36DC", "Pink"),
                    ("#A258FF", "Lavender"),
                    ("#585858", "Grey"),
                ],
                help_text="Select a color for map pins with this category",
                max_length=7,
                null=True,
                verbose_name="color",
            ),
        ),
        migrations.AddField(
            model_name="poicategory",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("culture", "Culture"),
                    ("gastronomy", "Gastronomy"),
                    ("health", "Health"),
                    ("house", "House"),
                    ("leisure", "Leisure"),
                    ("media", "Media"),
                    ("meeting_point", "Meeting point"),
                    ("mobility", "Mobility"),
                    ("office", "Office"),
                    ("other", "Other"),
                    ("service", "Service"),
                    ("shopping", "Shopping"),
                ],
                help_text="Select an icon for this category",
                max_length=256,
                null=True,
                verbose_name="icon",
            ),
        ),
    ]
