# Generated by Django 3.2.16 on 2023-01-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0060_user_distribute_sidebar_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='stops',
            field=models.CharField(blank=True, help_text='List here the stops for public transport in the vicinity', max_length=250, verbose_name='Stops in the vicinity'),
        ),
    ]
