# Generated by Django 3.2.16 on 2023-01-30 16:08

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add field for en-/dis-abling machine translations to language tree model
    """

    dependencies = [
        ("cms", "0061_add_poi_organization_barrier-free"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagetreenode",
            name="machine_translation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable or disable machine translations into this language",
                verbose_name="machine translatable",
            ),
        ),
    ]
