# Generated by Django 3.2.16 on 2023-01-30 10:11

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Update fields for media files and media directories to add the option to make them hidden
    """

    dependencies = [
        ("cms", "0062_alter_languagetreenode"),
    ]

    operations = [
        migrations.AddField(
            model_name="directory",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Whether the directory is hidden in the regional media library",
                verbose_name="hidden",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Whether the media file is hidden in the regional media library",
                verbose_name="hidden",
            ),
        ),
    ]
