# Generated by Django 3.2.18 on 2023-02-28 10:27

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds the hix_ignore page setting to the model.
    """

    dependencies = [
        ("cms", "0063_add_is_hidden_field_to_global_media_library"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="hix_ignore",
            field=models.BooleanField(
                default=False,
                help_text="This allows to ignore HIX value for this specific page.",
                verbose_name="Ignore HIX value",
            ),
        ),
    ]
