# Generated by Django 3.2.18 on 2023-03-22 10:43

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds a hix score field to page translations
    """

    dependencies = [
        ("cms", "0064_page_hix_ignore"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetranslation",
            name="hix_score",
            field=models.FloatField(null=True, blank=True, verbose_name="HIX score"),
        ),
    ]
