# Generated by Django 3.2.18 on 2023-03-30 07:37

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add field to store previous "automatic translation" setting
    """

    dependencies = [
        ("cms", "0066_update_poi_translation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtranslation",
            name="automatic_translation",
            field=models.BooleanField(
                default=False,
                help_text="Tick if updating this content should automatically refresh or create its translations.",
                verbose_name="Automatic translation",
            ),
        ),
        migrations.AddField(
            model_name="imprintpagetranslation",
            name="automatic_translation",
            field=models.BooleanField(
                default=False,
                help_text="Tick if updating this content should automatically refresh or create its translations.",
                verbose_name="Automatic translation",
            ),
        ),
        migrations.AddField(
            model_name="pagetranslation",
            name="automatic_translation",
            field=models.BooleanField(
                default=False,
                help_text="Tick if updating this content should automatically refresh or create its translations.",
                verbose_name="Automatic translation",
            ),
        ),
        migrations.AddField(
            model_name="poitranslation",
            name="automatic_translation",
            field=models.BooleanField(
                default=False,
                help_text="Tick if updating this content should automatically refresh or create its translations.",
                verbose_name="Automatic translation",
            ),
        ),
    ]
