# Generated by Django 3.2.18 on 2023-04-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add the archived field to the feedback model
    """

    dependencies = [
        ("cms", "0067_add_automatic_translation_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the feedback is archived",
                verbose_name="archived",
            ),
        ),
    ]
