# Generated by Django 3.2.18 on 2023-05-23 12:04

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Rename database field and verbose name of external news
    """

    dependencies = [
        ("cms", "0070_alter_poicategory_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="region",
            old_name="tunews_enabled",
            new_name="external_news_enabled",
        ),
        migrations.AlterField(
            model_name="region",
            name="external_news_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable to display external articles in addition to local news managed by the CMS",
                verbose_name="Enable external news",
            ),
        ),
    ]
