# Generated by Django 3.2.19 on 2023-07-03 11:58

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add specific icons for shelterless people to selection for location categories
    """

    dependencies = [
        ("cms", "0071_update_external_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poicategory",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("advice", "Advice"),
                    ("culture", "Culture"),
                    ("daily_routine", "Daily routine"),
                    ("education", "Education"),
                    ("finance", "Finance"),
                    ("gastronomy", "Gastronomy"),
                    ("health", "Health"),
                    ("house", "House"),
                    ("leisure", "Leisure"),
                    ("media", "Media"),
                    ("medical_aid", "Medical aid"),
                    ("meeting_point", "Meeting point"),
                    ("mobility", "Mobility"),
                    ("office", "Office"),
                    ("other", "Other"),
                    ("other_help", "Other help"),
                    ("service", "Service"),
                    ("shopping", "Shopping"),
                    ("structure", "Structure"),
                ],
                help_text="Select an icon for this category",
                max_length=256,
                null=True,
                verbose_name="icon",
            ),
        ),
    ]
