# Generated by Django 3.2.19 on 2023-07-04 14:49

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add website to organization
    """

    dependencies = [
        ("cms", "0072_alter_poicategory_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(default="", max_length=250, verbose_name="website"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.URLField(max_length=250, verbose_name="website"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="icon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="icon_organizations",
                to="cms.mediafile",
                verbose_name="logo",
            ),
        ),
    ]
