# Generated by Django 3.2.19 on 2023-07-16 17:10

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add a field to push notification to indicate when they should be sent
    """

    dependencies = [
        ("cms", "0073_add_organization_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushnotification",
            name="scheduled_send_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The scheduled date for this push notification to be sent",
                null=True,
                verbose_name="scheduled send date",
            ),
        ),
    ]
