# Generated by Django 3.2.20 on 2023-07-28 08:15

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adjusting the help text of the field `deepl_addon_booked`
    """

    dependencies = [
        ("cms", "0076_add_push_notification_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="deepl_addon_booked",
            field=models.BooleanField(
                default=False,
                help_text="This makes 1000000 translation credits available to the region in addition to the 50000 free ones.",
                verbose_name="DeepL add-on package booked",
            ),
        ),
    ]
