# Generated by Django 3.2.20 on 2023-10-17 13:25

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This file alters the help text for the export mode info box
    """

    dependencies = [
        ("cms", "0081_poi_appointment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="expert_mode",
            field=models.BooleanField(
                default=False,
                help_text="Enable this option to display additional features like XLIFF import/export, page filtering, mirrored pages, page-based permissions and status information for broken links",
                verbose_name="experienced user",
            ),
        ),
    ]
