# Generated by Django 3.2.22 on 2023-12-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add translatable socialmedia title
    """

    dependencies = [
        ("cms", "0083_add_page_based_offer_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="socialmedia_webapp_title",
            field=models.CharField(
                default="Integreat | Web-App | Lokale Informationen für Dich",
                help_text="Displayed title of the WebApp in the search results and on socialmedia pages.",
                max_length=250,
                verbose_name="Socialmedia title of the WebApp",
            ),
        ),
    ]
