# Generated by Django 3.2.23 on 2023-11-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Change wording of "review" to "approval"
    """

    dependencies = [
        ("cms", "0084_add_zammad_forms_as_offers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtranslation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REVIEW", "Pending Approval"),
                    ("PUBLIC", "Published"),
                    ("AUTO_SAVE", "Auto Save"),
                ],
                default="DRAFT",
                max_length=9,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="imprintpagetranslation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REVIEW", "Pending Approval"),
                    ("PUBLIC", "Published"),
                    ("AUTO_SAVE", "Auto Save"),
                ],
                default="DRAFT",
                max_length=9,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="pagetranslation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REVIEW", "Pending Approval"),
                    ("PUBLIC", "Published"),
                    ("AUTO_SAVE", "Auto Save"),
                ],
                default="DRAFT",
                max_length=9,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="poitranslation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REVIEW", "Pending Approval"),
                    ("PUBLIC", "Published"),
                    ("AUTO_SAVE", "Auto Save"),
                ],
                default="DRAFT",
                max_length=9,
                verbose_name="status",
            ),
        ),
    ]
