# Generated by Django 3.2.23 on 2024-01-19 22:55

import django.db.models.constraints
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0084_add_zammad_forms_as_offers"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "lft"),
                name="unique_lft_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "rgt"),
                name="unique_rgt_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.CheckConstraint(
                check=models.Q(("lft__lt", django.db.models.expressions.F("rgt"))),
                name="check_rgt_greater_lft",
            ),
        ),
    ]
