# Generated by Django 4.2.10 on 2024-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0086_alter_fields_for_django_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="socialmedia_webapp_title",
            field=models.CharField(
                blank=True,
                help_text="Displayed title of the WebApp in the search results and on socialmedia pages.",
                max_length=250,
                verbose_name="Socialmedia title of the WebApp",
            ),
        ),
    ]
