# Generated by Django 3.2.23 on 2024-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add field for preferred machine translation provider per language.
    """

    dependencies = [
        ("cms", "0086_alter_fields_for_django_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagetreenode",
            name="preferred_mt_provider",
            field=models.CharField(
                choices=[("DeepL", "DeepL"), ("SUMM.AI", "SUMM.AI")],
                default="DeepL",
                help_text="Preferred provider for translations into this language",
                max_length=255,
                verbose_name="machine translation provider",
            ),
        ),
    ]
