# Generated by Django 4.2.10 on 2024-03-01 18:10

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add (deferrable) contraints for the page tree
    """

    dependencies = [
        ("cms", "0088_rename_mt_related_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "lft"),
                name="unique_lft_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "rgt"),
                name="unique_rgt_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.CheckConstraint(
                check=models.Q(("lft__lt", models.F("rgt"))),
                name="check_rgt_greater_lft",
            ),
        ),
    ]
