# Generated by Django 4.2.10 on 2024-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0088_rename_mt_related_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="language_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FFBB78", "Amharic"),
                    ("2CA02C", "Arabic"),
                    ("C5B0D5", "Czech"),
                    ("FF4500", "German"),
                    ("FFA500", "German easy"),
                    ("17157D", "Greek"),
                    ("1F77B4", "English"),
                    ("FFD700", "Spanish"),
                    ("008080", "Persian"),
                    ("9EDAE5", "Finnish"),
                    ("5894E3", "French"),
                    ("17BECF", "Croatian"),
                    ("FF6347", "Hungarian"),
                    ("98DF8A", "Italian"),
                    ("9467BD", "Kurdish"),
                    ("ADFF2F", "Sorani"),
                    ("E377C2", "Kurmanji"),
                    ("8C564B", "Dutch"),
                    ("FFA07A", "Polish"),
                    ("FFE4F0", "Dari"),
                    ("F0E68C", "Brazilian Portuguese"),
                    ("BCBD22", "Portuguese"),
                    ("800080", "Romanian"),
                    ("BA55D3", "Russian"),
                    ("DBDB8D", "Somali"),
                    ("4B5563", "Albanian"),
                    ("C49C94", "Serbian"),
                    ("7F7F7F", "Tigrinya"),
                    ("26FCFF", "Turkish"),
                    ("20B2AA", "Ukranian"),
                    ("FFDAB9", "Urdu"),
                    ("D62728", "Chinese simplified"),
                ],
                help_text="This is used to represent color label of the language",
                max_length=7,
                null=True,
                verbose_name="color",
            ),
        ),
    ]
