# Generated by Django 4.2.10 on 2024-04-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add field to store HIX feedback to the page translation model
    """

    dependencies = [
        ("cms", "0089_add_poicategory_icons"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetranslation",
            name="hix_feedback",
            field=models.JSONField(blank=True, null=True, verbose_name="HIX feedback"),
        ),
    ]
