# Generated by Django 4.2.10 on 2024-03-28 18:24

from django.db import migrations, models
from webauthn.helpers import generate_user_handle


class Migration(migrations.Migration):
    """
    Add a webauthn id bytes field to the user model
    """

    dependencies = [
        ("cms", "0090_pagetranslation_hix_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="webauthn_id",
            field=models.BinaryField(
                default=generate_user_handle,
            ),
        ),
    ]
