# Generated by Django 4.2.10 on 2024-04-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Riddle me this
    """

    dependencies = [
        ("cms", "0091_user_webauthn_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
