# Generated by Django 4.2.10 on 2024-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file to add the name field to external calendars.
    """

    dependencies = [
        ("cms", "0091_add_external_calendar_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcalendar",
            name="name",
            field=models.CharField(
                default="", max_length=255, verbose_name="calendar name"
            ),
        ),
    ]
