# Generated by Django 4.2.13 on 2024-06-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add field for toggling the Integreat Chat
    """

    dependencies = [
        ("cms", "0094_add_userchat_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="integreat_chat_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Toggle the Integreat Chat on/off.",
                verbose_name="Enable Integreat Chat",
            ),
        ),
    ]
