# Generated by Django 4.2.13 on 2024-07-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Change max_length of push notification content field from 250 to 500
    """

    dependencies = [
        ("cms", "0096_chat_beta_testing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotificationtranslation",
            name="text",
            field=models.TextField(blank=True, max_length=500, verbose_name="content"),
        ),
    ]
