# Generated by Django 4.2.13 on 2024-07-21 12:18

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add (deferrable) constraints for the page tree and language nodes
    """

    dependencies = [
        ("cms", "0097_alter_pushnotificationtranslation_text"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "lft"),
                name="page_unique_lft_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "rgt"),
                name="page_unique_rgt_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.CheckConstraint(
                check=models.Q(("lft__lt", models.F("rgt"))),
                name="page_check_rgt_greater_lft",
            ),
        ),
        migrations.AddConstraint(
            model_name="languagetreenode",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "lft"),
                name="languagetreenode_unique_lft_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="languagetreenode",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "rgt"),
                name="languagetreenode_unique_rgt_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="languagetreenode",
            constraint=models.CheckConstraint(
                check=models.Q(("lft__lt", models.F("rgt"))),
                name="languagetreenode_check_rgt_greater_lft",
            ),
        ),
    ]
