# Generated by Django 4.2.13 on 2024-08-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0097_alter_pushnotificationtranslation_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirebaseStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("region", models.CharField(max_length=100)),
                ("language_slug", models.CharField(max_length=2)),
                ("count", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
