# Generated by Django 4.2.13 on 2024-09-11 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds related name to poi in contact model
    """

    dependencies = [
        ("cms", "0101_external_calendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="poi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="cms.poi",
                verbose_name="POI",
            ),
        ),
    ]
