# Generated by Django 4.2.13 on 2024-10-06 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file that adds the field created by to external calendars
    """

    dependencies = [
        ("cms", "0106_update_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcalendar",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The account that created this external calendar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
    ]
