# Generated by Django 4.2.13 on 2024-10-02 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to introduce ContactUsage model for tracking where contacts are embedded
    """

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cms", "0106_update_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("field", models.CharField(max_length=128)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="cms.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="contactusage",
            constraint=models.UniqueConstraint(
                fields=("contact", "content_type", "object_id", "field"),
                name="contactusage_unique_combination",
            ),
        ),
    ]
