# Generated by Django 4.2.16 on 2024-11-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add a new field statistics_tutorial_seen to User model
    """

    dependencies = [
        ("cms", "0110_region_zammad_webhook_token_alter_region_zammad_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="statistics_tutorial_seen",
            field=models.BooleanField(
                default=False,
                help_text="Will be set to true once the user dismissed the tutorial for page access statistics",
                verbose_name="Page access statistics tutorial seen",
            ),
        ),
    ]
