# Generated by Django 4.2.16 on 2025-03-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file to add mobile number and fax to contact and to change the max length of phone number to 40
    """

    dependencies = [
        ("cms", "0118_rename_weekdays_in_events"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="contact_non_empty",
        ),
        migrations.AddField(
            model_name="contact",
            name="fax_number",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="fax number"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="mobile_phone_number",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="mobile phone number"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="phone number"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("area_of_responsibility", ""), _negated=True),
                    models.Q(("name", ""), _negated=True),
                    models.Q(("email", ""), _negated=True),
                    models.Q(("phone_number", ""), _negated=True),
                    models.Q(("mobile_phone_number", ""), _negated=True),
                    models.Q(("fax_number", ""), _negated=True),
                    models.Q(("website", ""), _negated=True),
                    _connector="OR",
                ),
                name="contact_non_empty",
                violation_error_message="One of the following fields must be filled: area of responsibility, name, e-mail, phone number, mobile phone number, fax number, website.",
            ),
        ),
    ]
