# Generated by Django 4.2.16 on 2025-03-19 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0120_remove_fax_number_from_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "default_permissions": ("change", "delete", "view", "archive"),
                "default_related_name": "contact",
                "ordering": ["location", "name"],
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
    ]
