# Generated by Django 4.2.16 on 2025-03-12 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0120_remove_fax_number_from_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userchat",
            name="most_recent_hits",
        ),
        migrations.DeleteModel(
            name="AttachmentMap",
        ),
    ]
