# Generated by Django 4.2.16 on 2025-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0122_add_do_not_translate_title_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="type",
            field=models.CharField(
                choices=[
                    ("image/svg+xml", "SVG image"),
                    ("image/png", "PNG image"),
                    ("image/jpeg", "JPEG image"),
                    ("application/pdf", "PDF document"),
                    ("image/gif", "GIF image"),
                    ("application/msword", "DOC document"),
                    (
                        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                        "DOCX document",
                    ),
                    ("application/vnd.ms-excel", "XLS document"),
                    (
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "XLSX document",
                    ),
                    ("application/vnd.ms-powerpoint", "PPT document"),
                    (
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "PPTX document",
                    ),
                ],
                max_length=128,
                verbose_name="file type",
            ),
        ),
    ]
