# Generated by Django 4.2.16 on 2025-03-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0122_event_do_not_translate_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="do_not_translate_title",
            field=models.BooleanField(
                default=False,
                help_text="Tick if you do not want to translate the title by automatic translation.",
                verbose_name="do not translate the title",
            ),
        ),
        migrations.AlterField(
            model_name="imprintpage",
            name="do_not_translate_title",
            field=models.BooleanField(
                default=False,
                help_text="Tick if you do not want to translate the title by automatic translation.",
                verbose_name="do not translate the title",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="do_not_translate_title",
            field=models.BooleanField(
                default=False,
                help_text="Tick if you do not want to translate the title by automatic translation.",
                verbose_name="do not translate the title",
            ),
        ),
        migrations.AlterField(
            model_name="poi",
            name="do_not_translate_title",
            field=models.BooleanField(
                default=False,
                help_text="Tick if you do not want to translate the title by automatic translation.",
                verbose_name="do not translate the title",
            ),
        ),
    ]
