# Generated by Django 4.2.16 on 2025-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0122_add_do_not_translate_title_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="has_physical_location",
            field=models.BooleanField(
                default=True,
                help_text="Whether the event has a physical location.",
                verbose_name="Has physical location",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="online_link",
            field=models.URLField(
                blank=True,
                help_text="Link to the online event if it has no physical location.",
                verbose_name="Online event link",
            ),
        ),
    ]
