# Generated by Django 4.2.16 on 2025-04-30 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0127_hide_page_based_statistics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="statistics_tutorial_seen",
        ),
    ]
