# Generated by Django 4.2.16 on 2025-04-04 15:06
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0128_remove_user_statistics_tutorial_seen"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="region",
            name="zammad_chat_handlers",
        ),
        migrations.AddField(
            model_name="region",
            name="zammad_privacy_policy",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Link to custom privacy policy for self-hosted Zammad server.",
                max_length=1024,
                verbose_name="Custom Integreat Chat privacy policy",
            ),
        ),
    ]
