# Generated by Django 4.2.16 on 2025-05-08 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0129_remove_region_zammad_chat_handlers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="chat_beta_tester_percentage",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Percentage of users selected as beta testers for the public chat feature",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Chat beta tester percentage",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="integreat_chat_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Toggle the public chat (chat bot) on/off.",
                verbose_name="Enable public chat",
            ),
        ),
    ]
