# Generated by Django 4.2.16 on 2025-05-07 14:37

from typing import Any
from django.db import migrations, models


def fix_language_visibility(apps: Any, _: object) -> None:
    LanguageTreeNode = apps.get_model("cms", "LanguageTreeNode")
    LanguageTreeNode.objects.filter(active=False, visible=True).update(visible=False)


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0129_remove_region_zammad_chat_handlers_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_language_visibility),
        migrations.RemoveConstraint(
            model_name="languagetreenode",
            name="languagetreenode_unique_lft_tree",
        ),
        migrations.RemoveConstraint(
            model_name="languagetreenode",
            name="languagetreenode_unique_rgt_tree",
        ),
        migrations.RemoveConstraint(
            model_name="languagetreenode",
            name="languagetreenode_check_rgt_greater_lft",
        ),
        migrations.AddConstraint(
            model_name="languagetreenode",
            constraint=models.CheckConstraint(
                check=models.Q(("active", False), ("visible", True), _negated=True),
                name="language_tree_node_inactive_requires_invisible",
                violation_error_message="An inactive language tree node has to be invisible.",
            ),
        ),
    ]
