# Generated by Django 4.2.16 on 2025-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0129_remove_region_zammad_chat_handlers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("HIDDEN", "Hidden"),
                    ("ARCHIVED", "Archived"),
                    ("IN_CLONING", "Currently in cloning"),
                ],
                default="HIDDEN",
                max_length=25,
                verbose_name="status",
            ),
        ),
    ]
