# Generated by Django 4.2.16 on 2025-05-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0130_rename_chats"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="languagetreenode",
            constraint=models.CheckConstraint(
                check=models.Q(("active", False), ("visible", True), _negated=True),
                name="language_tree_node_inactive_requires_invisible",
                violation_error_message="An inactive language tree node has to be invisible.",
            ),
        ),
    ]
