# Generated by Django 4.2.16 on 2025-06-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0135_add_opening_hours_for_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="online_link",
            field=models.URLField(
                blank=True,
                help_text="Link to the online event if it has no physical location.",
                verbose_name="Online event link",
            ),
        ),
    ]
