# Generated by Django 4.2.16 on 2025-06-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0136_event_online_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="online_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link to the online event if it has no physical location.",
                verbose_name="Online event link",
            ),
        ),
    ]
