# Generated by Django 4.2.16 on 2025-06-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0136_event_online_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageaccesses",
            name="access_date",
            field=models.DateField(verbose_name="Date of the page accesses"),
        ),
    ]
