# Generated by Django 4.2.16 on 2025-07-07 06:24

from typing import Any

import django.db.models.deletion
from django.db import migrations, models

from integreat_cms.cms.utils.slug_utils import generate_unique_slug


def make_slugs_unique(apps: Any, _schema_editor: Any) -> None:
    EventTranslation = apps.get_model("cms", "EventTranslation")
    PageTranslation = apps.get_model("cms", "PageTranslation")
    POITranslation = apps.get_model("cms", "POITranslation")
    for translation in EventTranslation.objects.all():
        region = getattr(translation.event, "region", None)
        if not region:
            continue
        translation.slug = generate_unique_slug(
            slug=translation.slug,
            manager=type(translation).objects,
            object_instance=translation,
            foreign_model="event",
            foreign_object=translation.event,
            region=region,
            language=translation.language,
        )
        translation.save()

    for translation in PageTranslation.objects.all():
        region = getattr(translation.page, "region", None)
        if not region:
            continue
        translation.slug = generate_unique_slug(
            slug=translation.slug,
            manager=type(translation).objects,
            object_instance=translation,
            foreign_model="page",
            foreign_object=translation.page,
            region=region,
            language=translation.language,
        )
        translation.save()

    for translation in POITranslation.objects.all():
        region = getattr(translation.poi, "region", None)
        if not region:
            continue
        translation.slug = generate_unique_slug(
            slug=translation.slug,
            manager=type(translation).objects,
            object_instance=translation,
            foreign_model="poi",
            foreign_object=translation.poi,
            region=region,
            language=translation.language,
        )
        translation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0138_configurable_mt_budget"),
    ]

    operations = [
        migrations.RunPython(make_slugs_unique, migrations.RunPython.noop),
        migrations.AddField(
            model_name="pagetranslation",
            name="region",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cms.region",
            ),
        ),
    ]
