# Generated by Django 4.2.16 on 2025-06-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0138_rename_online_link_event_meeting_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="meeting_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the online event if it has no physical location.",
                null=True,
                verbose_name="Online event link",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("meeting_url", None), ("location", None), _connector="OR"
                ),
                name="meeting_url_requires_no_location",
                violation_error_message="An event with a location can't have a meeting URL",
            ),
        ),
    ]
