# Generated by Django 4.2.16 on 2025-07-15 17:17

from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def forwards_func(
    apps: Apps,
    _schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    """
    Data migration step attempting to fix all trees
    to remove any lingering inconsistencies before adding constraints
    """
    Event = apps.get_model("cms", "Event")
    for event in Event.objects.all():
        if event.online_link:
            if event.location:
                # event.location and event.online_link are both set, which is not allowed.
                # Therefore remove the online_link. This only happens when the online_link was set first and location was added.
                event.online_link = ""
            else:
                event.meeting_url = event.online_link
            event.save()


def reverse_func(
    apps: Apps,
    _schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    """
    Data migration when reverting this migration
    (nothing to do since the data is already consistent)
    """
    Event = apps.get_model("cms", "Event")
    for event in Event.objects.all():
        if event.meeting_url:
            event.online_link = event.meeting_url
            event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0138_configurable_mt_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="meeting_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link to the online event if it has no physical location.",
                verbose_name="Online event link",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("meeting_url", ""), ("location", None), _connector="OR"
                ),
                name="meeting_url_requires_no_location",
                violation_error_message="An event with a location can't have a meeting URL",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name="event",
            name="online_link",
        ),
    ]
