# Generated by Django 4.2.16 on 2025-06-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0138_configurable_mt_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="contacts_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not contacts are enabled in the region",
                verbose_name="activate contacts",
            ),
        ),
    ]
