# Generated by Django 4.2.16 on 2025-07-07 06:24

from typing import Any, TYPE_CHECKING

from django.db import migrations

from integreat_cms.cms.models.events.event_translation import EventTranslation
from integreat_cms.cms.models.pages.page_translation import PageTranslation
from integreat_cms.cms.models.pois.poi_translation import POITranslation
from integreat_cms.cms.utils.slug_utils import generate_unique_slug

if TYPE_CHECKING:
    from integreat_cms.cms.utils.slug_utils import SlugKwargs


def make_slugs_unique(_apps: Any, _schema_editor: Any) -> None:
    for translation in EventTranslation.objects.all():
        kwargs1: SlugKwargs = {
            "slug": translation.slug,
            "manager": type(translation).objects,
            "object_instance": translation,
            "foreign_model": "event",
            "foreign_object": translation.event,
            "region": translation.event.region,
            "language": translation.language,
        }
        translation.slug = generate_unique_slug(**kwargs1)
        translation.save()

    for translation in PageTranslation.objects.all():
        kwargs2: SlugKwargs = {
            "slug": translation.slug,
            "manager": type(translation).objects,
            "object_instance": translation,
            "foreign_model": "page",
            "foreign_object": translation.page,
            "region": translation.page.region,
            "language": translation.language,
        }
        translation.slug = generate_unique_slug(**kwargs2)
        translation.save()

    for translation in POITranslation.objects.all():
        kwargs3: SlugKwargs = {
            "slug": translation.slug,
            "manager": type(translation).objects,
            "object_instance": translation,
            "foreign_model": "poi",
            "foreign_object": translation.poi,
            "region": translation.poi.region,
            "language": translation.language,
        }
        translation.slug = generate_unique_slug(**kwargs3)
        translation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0138_configurable_mt_budget"),
    ]

    operations = [
        migrations.RunPython(make_slugs_unique),
    ]
