# Generated by Django 4.2.16 on 2025-08-05 07:53

from typing import Any

import django.contrib.postgres.constraints
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


def set_region_id(apps: Any, _schema_editor: Any) -> None:
    PageTranslation = apps.get_model("cms", "PageTranslation")
    for pt in PageTranslation.objects.all():
        pt.region_id = pt.page.region_id
        pt.save(update_fields=["region_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0139_make_existing_slugs_unique"),
    ]

    operations = [
        migrations.RunPython(set_region_id, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gist;",
            reverse_sql="DROP EXTENSION IF EXISTS btree_gist;",
        ),
        migrations.AddConstraint(
            model_name="pagetranslation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (models.F("slug"), "="),
                    (models.F("language"), "="),
                    (models.F("region"), "="),
                    (models.F("page"), "<>"),
                ],
                name="exclude_same_slug_lang_region_diff_page",
            ),
        ),
    ]
