# Generated by Django 4.2.16 on 2025-05-26 17:01

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def fix_inactive_visible_nodes(
    apps: Apps, _schema_editor: BaseDatabaseSchemaEditor
) -> None:
    LanguageTreeNode = apps.get_model("cms", "LanguageTreeNode")
    LanguageTreeNode.objects.filter(active=False, visible=True).update(visible=False)


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0140_rename_online_link_event_meeting_url"),
    ]

    operations = [
        migrations.RunPython(
            fix_inactive_visible_nodes, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="languagetreenode",
            constraint=models.CheckConstraint(
                check=models.Q(("active", False), ("visible", True), _negated=True),
                name="language_tree_node_inactive_requires_invisible",
                violation_error_message="An inactive language tree node has to be invisible.",
            ),
        ),
    ]
