# Generated by Django 4.2.16 on 2025-08-06 09:31

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0140_pagetranslation_region_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="update_translations_on_region_change",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."region_id" IS DISTINCT FROM NEW."region_id")',
                    func="\n                BEGIN\n                    UPDATE cms_pagetranslation\n                    SET region_id = NEW.region_id\n                    WHERE page_id = NEW.id;\n                    RETURN NULL;\n                END;\n                ",
                    hash="8fccb948e514eece08c112000c8e22efc83b81d0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_translations_on_region_change_30a57",
                    table="cms_page",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pagetranslation",
            trigger=pgtrigger.compiler.Trigger(
                name="set_region_on_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                BEGIN\n                    SELECT region_id INTO NEW.region_id\n                    FROM cms_page\n                    WHERE id = NEW.page_id;\n                    RETURN NEW;\n                END;\n                ",
                    hash="bea2a8791e5b70efb5b9080904a9ce1c46973b3d",
                    operation="INSERT",
                    pgid="pgtrigger_set_region_on_insert_1b253",
                    table="cms_pagetranslation",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pagetranslation",
            trigger=pgtrigger.compiler.Trigger(
                name="set_region_on_page_change",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."page_id" IS DISTINCT FROM NEW."page_id")',
                    func="\n                BEGIN\n                    SELECT region_id INTO NEW.region_id\n                    FROM cms_page\n                    WHERE id = NEW.page_id;\n                    RETURN NEW;\n                END;\n                ",
                    hash="c3467e1a4861595aa53d6973d633a85afb348730",
                    operation="UPDATE",
                    pgid="pgtrigger_set_region_on_page_change_9ae59",
                    table="cms_pagetranslation",
                    when="BEFORE",
                ),
            ),
        ),
    ]
