# Generated by Django 5.2 on 2025-09-29 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0143_change_permission_page_based_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchat",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date and time when the chat was started.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userchat",
            name="last_message_timestamp",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the last chat message was sent.",
            ),
        ),
        migrations.AddField(
            model_name="userchat",
            name="total_words_generated",
            field=models.IntegerField(
                default=0, help_text="Number of words generated in this chat."
            ),
        ),
    ]
