# Generated by Django 4.2.16 on 2025-08-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0143_region_contacts_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="term_explanations_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not term explanations are enabled in the region",
                verbose_name="activate term explanations",
            ),
        ),
    ]
