# Generated by Django 4.2.16 on 2026-01-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0145_userchat_created_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pushnotification",
            name="draft",
        ),
        migrations.RemoveField(
            model_name="pushnotification",
            name="is_template",
        ),
        migrations.RemoveField(
            model_name="pushnotification",
            name="template_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="page_tree_tutorial_seen",
        ),
    ]
