# Generated by Django 4.2.16 on 2026-02-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0145_userchat_created_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='page_tree_tutorial_seen',
            new_name='has_seen_page_tree_tutorial'
        ),
        migrations.AlterField(
            model_name='user',
            name='has_seen_page_tree_tutorial',
            field=models.BooleanField(default=False, help_text='Has seen tutorial for page tree', verbose_name='Page tree tutorial seen'),
        ),
    ]
