# Generated by Django 4.2.16 on 2025-12-15 11:16

from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def copy_page_tree_tutorial_seen_forward(
    apps: Apps, _schema_editor: BaseDatabaseSchemaEditor
) -> None:
    User = apps.get_model("cms", "User")
    for user in User.objects.all():
        # If the old attribute exists, copy it; otherwise default False
        user.has_seen_page_tree_tutorial = bool(
            getattr(user, "page_tree_tutorial_seen", False)
        )
        user.save(update_fields=["has_seen_page_tree_tutorial"])


def copy_page_tree_tutorial_seen_backward(
    apps: Apps, _schema_editor: BaseDatabaseSchemaEditor
) -> None:
    User = apps.get_model("cms", "User")
    for user in User.objects.all():
        user.page_tree_tutorial_seen = bool(
            getattr(user, "has_seen_page_tree_tutorial", False)
        )
        user.save(update_fields=["page_tree_tutorial_seen"])


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0145_userchat_created_timestamp_and_more"),
    ]

    # No-op migration: the `has_seen_page_tree_tutorial` field already exists from the
    # initial migration (0001). The previous attempt to Add/Copy/Remove assumes an
    # older field named `page_tree_tutorial_seen` that is not present in history and
    # therefore causes a KeyError when building the migration state. Keeping this
    # migration as a no-op preserves numbering while avoiding errors.
    operations = [

    migrations.AddField(
        model_name="user",
        name="has_seen_page_tree_tutorial",
        field=models.BooleanField(default=False),
    ),


    migrations.RunPython(
        copy_page_tree_tutorial_seen_forward,
        copy_page_tree_tutorial_seen_backward,
    )
]
