# Generated by Django 4.2.16 on 2025-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0145_userchat_created_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="opening_hours",
        ),
        migrations.AddField(
            model_name="contact",
            name="office_hours",
            field=models.JSONField(blank=True, null=True, verbose_name="office hours"),
        ),
    ]
