# Generated by Django 4.2.26 on 2025-11-23 10:57

from django.db import migrations, models
import django.db.models.deletion

def fill_statistics_day(apps, schema_editor):
    """
    Populate the StatisticsDay model from existing data in PageAccesses
    """
    PageAccesses = apps.get_model("cms", "PageAccesses")
    StatisticsDay = apps.get_model("cms", "StatisticsDay")
    Region = apps.get_model("cms", "Region")
    for row in PageAccesses.objects.values("access_date", "page__region").distinct():
        region = Region.objects.get(id=row["page__region"])
        print(f"region id: {region}")
        statistics_day = StatisticsDay(access_date=row["access_date"], region=region)
        statistics_day.save()
        PageAccesses.objects.filter(
            page__region=row["page__region"], access_date=row["access_date"]
        ).update(statistics_day=statistics_day.pk)


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0145_userchat_created_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_date",
                    models.DateField(verbose_name="Date of the page accesses"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cms.region"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pageaccesses",
            name="statistics_day",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cms.statisticsday",
            ),
        ),
        migrations.RemoveConstraint(
            model_name='pageaccesses',
            name='pageaccesses_unique_version',
        ),
        migrations.AddConstraint(
            model_name='statisticsday',
            constraint=models.UniqueConstraint(fields=('access_date', 'region'), name='statisticsday_unique_version'),
        ),
        migrations.RunPython(fill_statistics_day),
    ]
