# Generated by Django 4.2.16 on 2025-12-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0145_userchat_created_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="page_tree_tutorial_seen",
        ),
        migrations.AddField(
            model_name="user",
            name="has_seen_page_tree_tutorial",
            field=models.BooleanField(
                default=False,
                help_text="Has seen tutorial for page tree",
                verbose_name="Page tree tutorial seen",
            ),
        ),
    ]
