# Generated by Django 4.2.16 on 2025-11-28 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0145_userchat_created_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pushnotification",
            name="draft",
        ),
        migrations.RemoveField(
            model_name="pushnotification",
            name="is_template",
        ),
        migrations.RemoveField(
            model_name="pushnotification",
            name="template_name",
        ),
    ]
