# Generated by Django 4.2.26 on 2025-11-23 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def remove_zero_hits(apps, schema_editor):
    """
    Populate the StatisticsDay model from existing data in PageAccesses
    """
    PageAccesses = apps.get_model("cms", "PageAccesses")
    PageAccesses.objects.filter(accesses=0).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0146_statisticsday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageaccesses",
            name="access_date",
        ),
        migrations.RunPython(remove_zero_hits),
        migrations.AlterField(
            model_name="pageaccesses",
            name="accesses",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Page accesses",
            ),
        ),
    ]