# Generated by Django 4.2.16 on 2025-12-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0146_remove_user_page_tree_tutorial_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_seen_page_tree_tutorial',
            field=models.BooleanField(default=False, help_text='Has seen tutorial for page tree', verbose_name='Page tree tutorial seen'),
        ),
    ]

