# Generated by Django 4.2.16 on 2026-01-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0147_adopt_new_phone_number_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="machine_translate_pushnotifications",
            field=models.PositiveIntegerField(
                choices=[(0, "No"), (1, "Yes"), (2, "Yes, only managers")],
                default=1,
                verbose_name="Push Notifications",
            ),
        ),
        migrations.AddField(
            model_name="pushnotification",
            name="do_not_translate_title",
            field=models.BooleanField(
                default=False,
                help_text="Tick if you do not want to translate the title by automatic translation.",
                verbose_name="do not translate the title",
            ),
        ),
        migrations.AddField(
            model_name="pushnotificationtranslation",
            name="automatic_translation",
            field=models.BooleanField(
                default=False,
                help_text="Tick if updating this content should automatically refresh or create its translations.",
                verbose_name="Automatic translation",
            ),
        ),
    ]
