# Generated by Django 5.2 on 2025-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0148_region_machine_translate_pushnotifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="opening_hours",
            field=models.JSONField(blank=True, null=True, verbose_name="office hours"),
        ),
    ]
