# Generated by Django 4.2.16 on 2026-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0150_remove_user_page_tree_tutorial_seen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotificationtranslation",
            name="title",
            field=models.CharField(max_length=250, verbose_name="title"),
        ),
    ]
