# Generated by Django 5.2 on 2026-04-27 14:42
from __future__ import annotations

from typing import TYPE_CHECKING

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def print_action_required(
    _apps: Apps, _schema_editor: BaseDatabaseSchemaEditor
) -> None:
    print("""
============================================================
ACTION REQUIRED: We have introduced database level constraints,
that do not allow duplicate slugs for pages, pois and events to
be entered into the database anymore.
For pre-existing duplicate slugs, please run the following
management command to fix those:

    integreat-cms-cli make_slugs_unique

This must be run after deployment.
============================================================
""")


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0152_remove_app_team_role"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="eventtranslation",
            trigger=pgtrigger.compiler.Trigger(
                name="enforce_slug_uniqueness",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                DECLARE\n                    new_region_id INTEGER;\n                BEGIN\n                    -- Look up the region for the new/updated event\n                    SELECT region_id INTO new_region_id\n                    FROM cms_event\n                    WHERE id = NEW.event_id;\n\n                    -- Set advisory lock (Postgresql specific)\n                    PERFORM pg_advisory_xact_lock(hashtextextended(NEW.language_id || ':' || new_region_id || ':' || NEW.slug, 0));\n\n                    -- Check if there's a conflict (same slug/language/region but different event)\n                    IF EXISTS (\n                        SELECT 1\n                        FROM cms_eventtranslation t\n                        JOIN cms_event p ON t.event_id = p.id\n                        WHERE t.slug = NEW.slug\n                        AND t.language_id = NEW.language_id\n                        AND p.region_id = new_region_id\n                        AND t.event_id <> NEW.event_id\n                    ) THEN\n                        RAISE EXCEPTION 'Slug must be unique per language and region across different event.' USING ERRCODE = 'unique_violation'; -- SQLSTATE 23505\n                    END IF;\n\n                    RETURN NEW;\n                END;\n                ",
                    hash="9a1f3f217ec3823189f83fa90064fb03cea3e7d8",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_enforce_slug_uniqueness_6fca2",
                    table="cms_eventtranslation",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pagetranslation",
            trigger=pgtrigger.compiler.Trigger(
                name="enforce_slug_uniqueness",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                DECLARE\n                    new_region_id INTEGER;\n                BEGIN\n                    -- Look up the region for the new/updated page\n                    SELECT region_id INTO new_region_id\n                    FROM cms_page\n                    WHERE id = NEW.page_id;\n\n                    -- Set advisory lock (Postgresql specific)\n                    PERFORM pg_advisory_xact_lock(hashtextextended(NEW.language_id || ':' || new_region_id || ':' || NEW.slug, 0));\n\n                    -- Check if there's a conflict (same slug/language/region but different page)\n                    IF EXISTS (\n                        SELECT 1\n                        FROM cms_pagetranslation t\n                        JOIN cms_page p ON t.page_id = p.id\n                        WHERE t.slug = NEW.slug\n                        AND t.language_id = NEW.language_id\n                        AND p.region_id = new_region_id\n                        AND t.page_id <> NEW.page_id\n                    ) THEN\n                        RAISE EXCEPTION 'Slug must be unique per language and region across different pages.' USING ERRCODE = 'unique_violation'; -- SQLSTATE 23505\n                    END IF;\n\n                    RETURN NEW;\n                END;\n                ",
                    hash="1bce88dd0f03e80bd0913addb9ed860c7589ca08",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_enforce_slug_uniqueness_5206b",
                    table="cms_pagetranslation",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="poitranslation",
            trigger=pgtrigger.compiler.Trigger(
                name="enforce_slug_uniqueness",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                DECLARE\n                    new_region_id INTEGER;\n                BEGIN\n                    -- Look up the region for the new/updated poi\n                    SELECT region_id INTO new_region_id\n                    FROM cms_poi\n                    WHERE id = NEW.poi_id;\n\n                    -- Set advisory lock (Postgresql specific)\n                    PERFORM pg_advisory_xact_lock(hashtextextended(NEW.language_id || ':' || new_region_id || ':' || NEW.slug, 0));\n\n                    -- Check if there's a conflict (same slug/language/region but different poi)\n                    IF EXISTS (\n                        SELECT 1\n                        FROM cms_poitranslation t\n                        JOIN cms_poi p ON t.poi_id = p.id\n                        WHERE t.slug = NEW.slug\n                        AND t.language_id = NEW.language_id\n                        AND p.region_id = new_region_id\n                        AND t.poi_id <> NEW.poi_id\n                    ) THEN\n                        RAISE EXCEPTION 'Slug must be unique per language and region across different pois.' USING ERRCODE = 'unique_violation'; -- SQLSTATE 23505\n                    END IF;\n\n                    RETURN NEW;\n                END;\n                ",
                    hash="f8f6dc7607c3165262ef1f444918cee1417ea926",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_enforce_slug_uniqueness_66ef4",
                    table="cms_poitranslation",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.RunPython(print_action_required, migrations.RunPython.noop),
    ]
