# Generated by Django 5.2 on 2026-06-25 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0153_enforce_slug_uniqueness"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="distribute_sidebar_boxes",
        ),
    ]
