# Generated by Django 5.2 on 2026-07-08 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0155_enforce_case_insensitive_slug_uniqueness"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="region",
            name="chat_enabled",
        ),
    ]
