# Generated by Django 5.2 on 2026-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0155_enforce_case_insensitive_slug_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="publication date"
            ),
        ),
        migrations.AddField(
            model_name="imprintpage",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="publication date"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="publication date"
            ),
        ),
        migrations.AddField(
            model_name="poi",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="publication date"
            ),
        ),
    ]
