# Generated by Django 5.2.16 on 2026-08-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0156_remove_region_chat_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushnotification",
            options={
                "default_permissions": ("change", "delete", "view", "archive"),
                "ordering": ["-created_date"],
                "permissions": (
                    ("send_push_notification", "Can send push notification"),
                ),
                "verbose_name": "news",
                "verbose_name_plural": "news",
            },
        ),
        migrations.AlterField(
            model_name="region",
            name="machine_translate_pushnotifications",
            field=models.PositiveIntegerField(
                choices=[(0, "No"), (1, "Yes"), (2, "Yes, only managers")],
                default=1,
                verbose_name="News",
            ),
        ),
    ]
