# Generated by Django 5.2 on 2026-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0158_eventtranslation_published_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtranslation",
            name="currently_in_machine_translation",
            field=models.BooleanField(
                default=False,
                help_text="Flag to indicate a translation is currently being processed by a machine translation task",
                verbose_name="currently in machine translation",
            ),
        ),
        migrations.AddField(
            model_name="imprintpagetranslation",
            name="currently_in_machine_translation",
            field=models.BooleanField(
                default=False,
                help_text="Flag to indicate a translation is currently being processed by a machine translation task",
                verbose_name="currently in machine translation",
            ),
        ),
        migrations.AddField(
            model_name="pagetranslation",
            name="currently_in_machine_translation",
            field=models.BooleanField(
                default=False,
                help_text="Flag to indicate a translation is currently being processed by a machine translation task",
                verbose_name="currently in machine translation",
            ),
        ),
        migrations.AddField(
            model_name="poitranslation",
            name="currently_in_machine_translation",
            field=models.BooleanField(
                default=False,
                help_text="Flag to indicate a translation is currently being processed by a machine translation task",
                verbose_name="currently in machine translation",
            ),
        ),
        migrations.AddField(
            model_name="pushnotificationtranslation",
            name="currently_in_machine_translation",
            field=models.BooleanField(
                default=False,
                help_text="Flag to indicate a translation is currently being processed by a machine translation task",
                verbose_name="currently in machine translation",
            ),
        ),
    ]
