# Generated by Django 5.2 on 2026-08-11 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0158_eventtranslation_published_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="token name")),
                (
                    "prefix",
                    models.BinaryField(
                        help_text="The public part of the token which is used to identify it. It is stored as raw bytes and hex encoded in the plaintext token.",
                        max_length=6,
                        unique=True,
                        verbose_name="token prefix",
                    ),
                ),
                (
                    "token_hash",
                    models.BinaryField(
                        help_text="The raw SHA-256 digest of the full plaintext token, i.e. of the hex encoded prefix, the separator and the secret.",
                        max_length=32,
                        verbose_name="token hash",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "last_usage",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last date of use"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "API token",
                "verbose_name_plural": "API tokens",
                "ordering": ["name"],
                "default_permissions": (),
                "unique_together": {("user", "name")},
            },
        ),
    ]
