# Generated by Django 5.2 on 2026-08-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0158_eventtranslation_published_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushnotification",
            options={
                "default_permissions": ("change", "delete", "view", "archive"),
                "ordering": ["-created_date"],
                "permissions": (
                    ("send_push_notification", "Can send push notification"),
                ),
                "verbose_name": "news",
                "verbose_name_plural": "news",
            },
        ),
        migrations.AlterModelOptions(
            name="pushnotificationtranslation",
            options={
                "default_permissions": (),
                "ordering": ["push_notification__pk", "language__pk", "language"],
                "verbose_name": "news translation",
                "verbose_name_plural": "news translations",
            },
        ),
        migrations.AlterField(
            model_name="pushnotificationtranslation",
            name="push_notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="cms.pushnotification",
                verbose_name="news",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="machine_translate_pushnotifications",
            field=models.PositiveIntegerField(
                choices=[(0, "No"), (1, "Yes"), (2, "Yes, only managers")],
                default=1,
                verbose_name="News",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="push_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not news is enabled in the region",
                verbose_name="activate news",
            ),
        ),
    ]
