# Generated by Django 5.2.16 on 2026-08-19 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0159_api_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushnotification",
            options={
                "default_permissions": ("change", "delete", "view", "archive"),
                "ordering": ["-created_date"],
                "permissions": (
                    ("send_push_notification", "Can send push notification"),
                ),
                "verbose_name": "news",
                "verbose_name_plural": "news",
            },
        ),
        migrations.AlterModelOptions(
            name="pushnotificationtranslation",
            options={
                "default_permissions": (),
                "ordering": ["push_notification__pk", "language__pk", "language"],
                "verbose_name": "news translation",
                "verbose_name_plural": "news translations",
            },
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the news item is read-only and hidden in the API.",
                verbose_name="archived",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ONLY_AVAILABLE", "Only send available translations"),
                    (
                        "USE_MAIN_LANGUAGE",
                        "Use main language if no translation is available",
                    ),
                ],
                help_text="Sets behavior for dealing with not existing news translations",
                max_length=128,
                verbose_name="mode",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="scheduled_send_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The scheduled date for this news item to be sent",
                null=True,
                verbose_name="scheduled send date",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="sent_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the news item was sent.",
                null=True,
                verbose_name="sent date",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotificationtranslation",
            name="push_notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="cms.pushnotification",
                verbose_name="news",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="machine_translate_pushnotifications",
            field=models.PositiveIntegerField(
                choices=[(0, "No"), (1, "Yes"), (2, "Yes, only managers")],
                default=1,
                verbose_name="News",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="push_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not news is enabled in the region",
                verbose_name="activate news",
            ),
        ),
    ]
