# Generated by Django 5.2.16 on 2026-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0159_news_wording"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotification",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the news is read-only and hidden in the API.",
                verbose_name="archived",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ONLY_AVAILABLE", "Only send available translations"),
                    (
                        "USE_MAIN_LANGUAGE",
                        "Use main language if no translation is available",
                    ),
                ],
                help_text="Sets behavior for dealing with not existing news translations",
                max_length=128,
                verbose_name="mode",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="scheduled_send_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The scheduled date for this news to be sent",
                null=True,
                verbose_name="scheduled send date",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="sent_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the news was sent.",
                null=True,
                verbose_name="sent date",
            ),
        ),
    ]
