# Generated by Django 5.2.16 on 2026-08-20 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0160_news_wording"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="expert_mode",
        ),
    ]
