# Generated by Django 5.2.14 on 2026-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0161_mt_budget_adjustment"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pagetranslation",
            index=models.Index(
                fields=["slug", "language", "page"], name="idx_pt_slug_lang_page"
            ),
        ),
    ]
